# rails-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app-deployment
  namespace: rails-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app-container
          image: ramyacloud001/rails-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_URL
              value: postgresql://postgres:password@postgres/db
